//! `brain docs generate` — always-up-to-date docs from the monolithic
//! binary. tour.md and the narration script are produced natively (the
//! narration's sentences are computed from graph queries, not parsed from
//! text). Media capture (Playwright screenshots + screencast), TTS, and
//! muxing shell out to environment tools when present — the .mjs/.py
//! helpers are embedded in the binary and written to a temp dir at run
//! time — and are skipped gracefully when absent, so the core projection
//! never fails for want of a browser.

use brain_observe::twin;
use brain_store::Store;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Embedded at compile time: the binary carries its whole pipeline.
const CAPTURE_MJS: &str = include_str!("../assets/capture.mjs");
const TTS_PY: &str = include_str!("../assets/tts.py");

pub fn cmd_docs(args: &[String], open_store: impl Fn() -> Result<Store, String>) -> Result<(), String> {
    let usage = "usage: brain docs generate [dir] [--prefix <p>] [--out <dir>]";
    if args.first().map(String::as_str) != Some("generate") {
        return Err(usage.to_string());
    }
    let mut dir = ".".to_string();
    let mut prefix = "twin/self".to_string();
    let mut out = "docs/generated".to_string();
    let mut it = args[1..].iter();
    let mut positional = false;
    while let Some(a) = it.next() {
        match a.as_str() {
            "--prefix" => prefix = it.next().cloned().ok_or(usage)?,
            "--out" => out = it.next().cloned().ok_or(usage)?,
            other if !other.starts_with("--") && !positional => {
                dir = other.to_string();
                positional = true;
            }
            other => return Err(format!("unexpected argument '{other}'\n{usage}")),
        }
    }
    generate(&open_store()?, Path::new(&dir), &prefix, Path::new(&out))
}

fn generate(store: &Store, dir: &Path, prefix: &str, out: &Path) -> Result<(), String> {
    twin::refresh(store, dir, prefix).map_err(|e| e.to_string())?;
    fs::create_dir_all(out.join("img")).map_err(|e| e.to_string())?;

    // ---- section outputs: the binary re-invokes itself, so every section
    // is exactly what a user would see, renderers included.
    let sections: Vec<(&str, Vec<&str>)> = vec![
        ("insights", vec!["twin", "insights", prefix]),
        ("matrix", vec!["feature", "matrix", prefix]),
        ("decisions", vec!["adr", "list", prefix]),
        ("tests", vec!["twin", "tests", prefix]),
        ("protocols", vec!["testrun", "list", prefix]),
        ("attention", vec!["attend", prefix]),
    ];
    let mut captured: Vec<(String, String, String)> = Vec::new(); // id, cmd, text
    for (id, args) in &sections {
        captured.push((id.to_string(), format!("brain {}", args.join(" ")), self_out(args)?));
    }
    let stale = self_out(&["twin", "stale", prefix])?;

    // ---- tour.md ---------------------------------------------------------
    let mut tour = String::new();
    tour.push_str(&format!(
        "# Live tour: `{prefix}`\n\n> Generated by `brain docs generate` from the graph.\n> Every section is a query result — regenerate, never edit.\n\n"
    ));
    let titles = [
        ("insights", "Insights (`brain twin insights`)"),
        ("matrix", "Feature matrix — definition of done (`brain feature matrix`)"),
        ("decisions", "Decisions (`brain adr list`)"),
        ("tests", "Tests (`brain twin tests`)"),
        ("protocols", "Test protocols (`brain testrun list`)"),
        ("attention", "Attention (`brain attend`)"),
    ];
    for ((_, title), (_, _, text)) in titles.iter().zip(&captured) {
        tour.push_str(&format!("## {title}\n```\n{text}\n```\n\n"));
    }
    tour.push_str(&format!("## Doc staleness (`brain twin stale`)\n```\n{stale}\n```\n\n"));
    tour.push_str("![insights](img/insights.png)\n\n![feature matrix](img/matrix.png)\n\n");
    tour.push_str("Screencast: [tour.webm](tour.webm) — narrated: [tour-narrated.webm](tour-narrated.webm)\n");
    fs::write(out.join("tour.md"), &tour).map_err(|e| e.to_string())?;

    // ---- narration: computed from the graph, not parsed from text --------
    let narration = narrate(store, prefix)?;
    fs::write(out.join("narration.txt"), &narration).map_err(|e| e.to_string())?;

    // ---- optional media steps -------------------------------------------
    let json: Vec<serde_json::Value> = captured
        .iter()
        .map(|(id, cmd, text)| serde_json::json!({"id": id, "cmd": cmd, "text": text}))
        .collect();
    fs::write(
        out.join(".sections.json"),
        serde_json::to_vec(&json).map_err(|e| e.to_string())?,
    )
    .map_err(|e| e.to_string())?;

    let tmp = std::env::temp_dir().join(format!("brain-docsgen-{}", std::process::id()));
    fs::create_dir_all(&tmp).map_err(|e| e.to_string())?;
    let capture = tmp.join("capture.mjs");
    let tts = tmp.join("tts.py");
    fs::write(&capture, CAPTURE_MJS).map_err(|e| e.to_string())?;
    fs::write(&tts, TTS_PY).map_err(|e| e.to_string())?;

    // Screenshots + screencast, when node/playwright are around.
    let mut node = Command::new("node");
    node.arg(&capture).arg(out).arg(prefix);
    if std::env::var_os("NODE_PATH").is_none() {
        if let Some(global) = npm_global_root() {
            node.env("NODE_PATH", global);
        }
    }
    match node.status() {
        Ok(s) if s.success() => {}
        Ok(_) => println!("docs: capture step failed (playwright unavailable?) — media skipped"),
        Err(_) => println!("docs: node not found — screenshots/screencast skipped"),
    }

    // TTS: Qwen3-TTS when its stack exists, espeak-ng fallback (see tts.py).
    let wav = out.join("tour.wav");
    match Command::new("python3")
        .arg(&tts)
        .arg(out.join("narration.txt"))
        .arg(&wav)
        .status()
    {
        Ok(s) if s.success() => {}
        Ok(_) => println!("docs: no TTS backend — narration.txt kept without audio"),
        Err(_) => println!("docs: python3 not found — TTS skipped"),
    }

    // Mux: full ffmpeg (system, or the imageio-ffmpeg static binary).
    let webm = out.join("tour.webm");
    if let Some(ffmpeg) = find_ffmpeg() {
        if webm.exists() && wav.exists() {
            mux(&ffmpeg, &webm, &wav, &out.join("tour-narrated.webm"))?;
            println!("docs: narrated screencast written");
        }
    } else if webm.exists() && wav.exists() {
        println!("docs: no full ffmpeg found — narrated mux skipped (pip install imageio-ffmpeg)");
    }

    let _ = fs::remove_file(out.join(".sections.json"));
    let _ = fs::remove_dir_all(&tmp);

    // The artifacts become part of the twin — marked as generated, so
    // attention and churn know their edits are projections, not work.
    twin::refresh(store, dir, prefix).map_err(|e| e.to_string())?;
    mark_generated(store, dir, out).map_err(|e| e.to_string())?;
    println!(
        "docs regenerated under {} (projection of {prefix}; do not edit)",
        out.display()
    );
    Ok(())
}

/// Guarded `generated=true` observations on every artifact under `out`.
fn mark_generated(
    store: &Store,
    dir: &Path,
    out: &Path,
) -> Result<(), brain_store::StoreError> {
    use brain_index::{replay, Index as _, MemIndex};
    let mut index = MemIndex::new();
    replay(store, &mut index)?;
    let now = brain_store::now_ms();
    let mut stack = vec![out.to_path_buf()];
    while let Some(d) = stack.pop() {
        for entry in std::fs::read_dir(&d)? {
            let path = entry?.path();
            if path.is_dir() {
                stack.push(path);
                continue;
            }
            // dir is often "." and read_dir yields already-relative paths;
            // a failed strip means the path is already repo-relative.
            let rel = path.strip_prefix(dir).unwrap_or(&path);
            let rel = rel.to_string_lossy().replace('\\', "/");
            let sid = brain_core::ids::StableId::derive(&["file", &rel]);
            if index.entity_nodes(&sid).is_empty() {
                continue; // not a twinned extension; nothing to mark
            }
            if twin::latest(&index, store, &sid, "generated")?.as_deref() != Some("true") {
                store.put(&brain_core::object::Object::Observation {
                    subject: sid,
                    property: "generated".to_string(),
                    value: "true".to_string(),
                    source: "docsgen".to_string(),
                    observed_at_ms: now,
                })?;
            }
        }
    }
    Ok(())
}

/// Narration computed straight from the graph — the audio track is as
/// regenerated (and as trustworthy) as the text.
pub fn narrate(store: &Store, prefix: &str) -> Result<String, String> {
    let ins = twin::insights(store, prefix).map_err(|e| e.to_string())?;
    let mut lines = vec![format!(
        "This is the live tour of {}, generated directly from the semantic graph.",
        prefix.replace('/', " ")
    )];
    lines.push(format!(
        "The twin currently tracks {} files, {} symbols, and {} relations.",
        ins.files, ins.symbols, ins.relations
    ));
    if ins.tests_declared > 0 {
        match ins.last_run {
            Some((_, total, passed, failed)) => {
                let verdict = if failed == 0 {
                    "all passing".to_string()
                } else {
                    format!("{failed} failing")
                };
                lines.push(format!(
                    "{} tests are declared; the last imported run had {passed} of {total} passing — {verdict}.",
                    ins.tests_declared
                ));
            }
            None => lines.push(format!("{} tests are declared.", ins.tests_declared)),
        }
    }
    if !ins.features.is_empty() {
        let done = ins.features.iter().filter(|(_, _, f)| {
            f.split_once('/').is_some_and(|(a, b)| a == b)
        }).count();
        lines.push(format!(
            "The feature matrix shows {} registered features, {done} of them meeting the full definition of done.",
            ins.features.len()
        ));
    }
    if !ins.decisions.is_empty() {
        lines.push(format!(
            "{} architecture decisions are recorded, each linked to the files it concerns.",
            ins.decisions.len()
        ));
    }
    if ins.stale_docs.is_empty() {
        lines.push(
            "No documentation is stale: every doc is newer than the files it mentions.".to_string(),
        );
    } else {
        lines.push(format!(
            "{} document(s) have gone stale and need attention.",
            ins.stale_docs.len()
        ));
    }
    lines.push(
        "Everything you just heard was a query, not prose — regenerate this tour any time with one command."
            .to_string(),
    );
    Ok(lines.join("\n"))
}

/// Run this same binary with args, capturing stdout.
fn self_out(args: &[&str]) -> Result<String, String> {
    let exe = std::env::current_exe().map_err(|e| e.to_string())?;
    let out = Command::new(exe).args(args).output().map_err(|e| e.to_string())?;
    if !out.status.success() {
        return Err(format!(
            "brain {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&out.stderr)
        ));
    }
    Ok(String::from_utf8_lossy(&out.stdout).trim_end().to_string())
}

fn npm_global_root() -> Option<PathBuf> {
    let known = Path::new("/opt/node22/lib/node_modules");
    if known.join("playwright").exists() {
        return Some(known.to_path_buf());
    }
    let out = Command::new("npm").args(["root", "-g"]).output().ok()?;
    let root = PathBuf::from(String::from_utf8_lossy(&out.stdout).trim());
    root.join("playwright").exists().then_some(root)
}

fn find_ffmpeg() -> Option<String> {
    for cand in ["ffmpeg"] {
        if Command::new(cand).arg("-version").output().is_ok_and(|o| o.status.success()) {
            return Some(cand.to_string());
        }
    }
    let out = Command::new("python3")
        .args(["-c", "import imageio_ffmpeg; print(imageio_ffmpeg.get_ffmpeg_exe())"])
        .output()
        .ok()?;
    if out.status.success() {
        let p = String::from_utf8_lossy(&out.stdout).trim().to_string();
        if !p.is_empty() {
            return Some(p);
        }
    }
    None
}

/// Probe a media file's duration in seconds via ffmpeg's -i banner.
fn duration_secs(ffmpeg: &str, file: &Path) -> Option<f64> {
    let out = Command::new(ffmpeg).arg("-i").arg(file).output().ok()?;
    let text = String::from_utf8_lossy(&out.stderr);
    let line = text.lines().find(|l| l.contains("Duration:"))?;
    let stamp = line.split("Duration:").nth(1)?.trim().split(',').next()?;
    let parts: Vec<&str> = stamp.split(':').collect();
    if parts.len() != 3 {
        return None;
    }
    let h: f64 = parts[0].parse().ok()?;
    let m: f64 = parts[1].parse().ok()?;
    let s: f64 = parts[2].parse().ok()?;
    Some(h * 3600.0 + m * 60.0 + s)
}

fn mux(ffmpeg: &str, webm: &Path, wav: &Path, out: &Path) -> Result<(), String> {
    let vdur = duration_secs(ffmpeg, webm).unwrap_or(0.0);
    let adur = duration_secs(ffmpeg, wav).unwrap_or(0.0);
    let pad = adur - vdur + 0.5;
    let status = if pad > 0.0 {
        // Narration outlasts the screencast: hold the last frame to its end.
        Command::new(ffmpeg)
            .args(["-y", "-loglevel", "error", "-i"])
            .arg(webm)
            .arg("-i")
            .arg(wav)
            .args(["-vf", &format!("tpad=stop_mode=clone:stop_duration={pad:.2}")])
            .args(["-c:v", "libvpx", "-b:v", "1M", "-c:a", "libopus"])
            .arg(out)
            .status()
    } else {
        Command::new(ffmpeg)
            .args(["-y", "-loglevel", "error", "-i"])
            .arg(webm)
            .arg("-i")
            .arg(wav)
            .args(["-c:v", "copy", "-c:a", "libopus", "-shortest"])
            .arg(out)
            .status()
    }
    .map_err(|e| e.to_string())?;
    if !status.success() {
        return Err("ffmpeg mux failed".to_string());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use brain_observe::twin::refresh;

    #[test]
    fn narration_is_computed_from_graph_state() {
        let src = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(src.path().join("src")).unwrap();
        std::fs::write(src.path().join("src/main.rs"), "pub fn main() {}\n#[test]\nfn t() {}\n")
            .unwrap();
        let store_dir = tempfile::tempdir().unwrap();
        let store = Store::open(store_dir.path()).unwrap();
        refresh(&store, src.path(), "twin/app").unwrap();

        let text = narrate(&store, "twin/app").unwrap();
        assert!(text.contains("twin app"), "prefix spoken: {text}");
        assert!(text.contains("1 files") || text.contains("tracks 1"), "file count spoken: {text}");
        assert!(text.contains("1 tests are declared"), "declared tests spoken: {text}");
        assert!(text.contains("No documentation is stale"));
        assert!(text.contains("regenerate this tour"));
    }
}
