//! `brain docs generate` — always-up-to-date docs from the monolithic
//! binary. tour.md and the narration script are produced natively (the
//! narration's sentences are computed from graph queries, not parsed from
//! text). Media capture (Playwright screenshots + screencast), TTS, and
//! muxing shell out to environment tools when present — the .mjs/.py
//! helpers are embedded in the binary and written to a temp dir at run
//! time — and are skipped gracefully when absent, so the core projection
//! never fails for want of a browser.

use brain_observe::{assets, tour, twin};
use brain_store::Store;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Embedded at compile time: the binary carries its whole pipeline.
const CAPTURE_MJS: &str = include_str!("../assets/capture.mjs");
const TTS_PY: &str = include_str!("../assets/tts.py");

pub fn cmd_docs(
    args: &[String],
    open_store: impl Fn() -> Result<Store, String>,
) -> Result<(), String> {
    let usage = "usage: brain docs generate [dir] [--prefix <p>] [--out <dir>]";
    if args.first().map(String::as_str) != Some("generate") {
        return Err(usage.to_string());
    }
    let mut dir = ".".to_string();
    let mut prefix = "twin/self".to_string();
    let mut out = "docs/generated".to_string();
    let mut it = args[1..].iter();
    let mut positional = false;
    while let Some(a) = it.next() {
        match a.as_str() {
            "--prefix" => prefix = it.next().cloned().ok_or(usage)?,
            "--out" => out = it.next().cloned().ok_or(usage)?,
            other if !other.starts_with("--") && !positional => {
                dir = other.to_string();
                positional = true;
            }
            other => return Err(format!("unexpected argument '{other}'\n{usage}")),
        }
    }
    generate(&open_store()?, Path::new(&dir), &prefix, Path::new(&out))
}

fn generate(store: &Store, dir: &Path, prefix: &str, out: &Path) -> Result<(), String> {
    twin::refresh(store, dir, prefix).map_err(|e| e.to_string())?;
    fs::create_dir_all(out.join("img")).map_err(|e| e.to_string())?;
    // The previous generation armed the read-only bit; the regenerator is
    // the one writer allowed to lower it.
    set_tree_writable(out);

    // ---- section outputs: the binary re-invokes itself, so every section
    // is exactly what a user would see, renderers included. The chapter
    // list lives in the graph crate because Eyes shows the same tour.
    let chapters = tour::chapters(prefix);
    let mut captured: Vec<(String, String, String)> = Vec::new(); // id, cmd, text
    for chapter in &chapters {
        let args: Vec<&str> = chapter.args.iter().map(String::as_str).collect();
        captured.push((
            chapter.id.to_string(),
            chapter.command(),
            self_out(&args)?,
        ));
    }
    let stale = self_out(&["twin", "stale", prefix])?;

    // ---- tour.md ---------------------------------------------------------
    let mut tour = String::new();
    tour.push_str(&format!(
        "# Live tour: `{prefix}`\n\n> Generated by `brain docs generate` from the graph.\n> Every section is a query result — regenerate, never edit.\n\n"
    ));
    for (chapter, (_, _, text)) in chapters.iter().zip(&captured) {
        tour.push_str(&format!("## {}\n```\n{text}\n```\n\n", chapter.title));
    }
    tour.push_str(&format!(
        "## Doc staleness (`brain twin stale`)\n```\n{stale}\n```\n\n"
    ));
    tour.push_str("![insights](img/insights.png)\n\n![feature matrix](img/matrix.png)\n\n");
    tour.push_str(
        "Screencast: [tour.webm](tour.webm) — narrated: [tour-narrated.webm](tour-narrated.webm)\n",
    );
    fs::write(out.join("tour.md"), &tour).map_err(|e| e.to_string())?;

    // ---- narration: computed from the graph, not parsed from text --------
    let narration = tour::narrate(store, prefix).map_err(|e| e.to_string())?;
    fs::write(out.join("narration.txt"), &narration).map_err(|e| e.to_string())?;

    // ---- optional media steps -------------------------------------------
    let json: Vec<serde_json::Value> = captured
        .iter()
        .map(|(id, cmd, text)| serde_json::json!({"id": id, "cmd": cmd, "text": text}))
        .collect();
    fs::write(
        out.join(".sections.json"),
        serde_json::to_vec(&json).map_err(|e| e.to_string())?,
    )
    .map_err(|e| e.to_string())?;

    let tmp = std::env::temp_dir().join(format!("brain-docsgen-{}", std::process::id()));
    fs::create_dir_all(&tmp).map_err(|e| e.to_string())?;
    let capture = tmp.join("capture.mjs");
    let tts = tmp.join("tts.py");
    fs::write(&capture, CAPTURE_MJS).map_err(|e| e.to_string())?;
    fs::write(&tts, TTS_PY).map_err(|e| e.to_string())?;

    // Screenshots + screencast, when node/playwright are around.
    let mut node = Command::new("node");
    node.arg(&capture).arg(out);
    if std::env::var_os("NODE_PATH").is_none() {
        if let Some(global) = npm_global_root() {
            node.env("NODE_PATH", global);
        }
    }
    match node.status() {
        Ok(s) if s.success() => {}
        Ok(_) => println!("docs: capture step failed (playwright unavailable?) — media skipped"),
        Err(_) => println!("docs: node not found — screenshots/screencast skipped"),
    }

    // TTS: Qwen3-TTS when its stack exists, espeak-ng fallback (see tts.py).
    let wav = out.join("tour.wav");
    match Command::new("python3")
        .arg(&tts)
        .arg(out.join("narration.txt"))
        .arg(&wav)
        .status()
    {
        Ok(s) if s.success() => {}
        Ok(_) => println!("docs: no TTS backend — narration.txt kept without audio"),
        Err(_) => println!("docs: python3 not found — TTS skipped"),
    }

    // Mux: full ffmpeg (system, or the imageio-ffmpeg static binary).
    // Like every other media step this degrades rather than aborting: a
    // failed mux must not cost us the man page and the projection marks.
    let webm = out.join("tour.webm");
    if let Some(ffmpeg) = find_ffmpeg() {
        if webm.exists() && wav.exists() {
            match mux(&ffmpeg, &webm, &wav, &out.join("tour-narrated.webm")) {
                Ok(()) => println!("docs: narrated screencast written"),
                Err(e) => println!("docs: {e} — narrated screencast skipped"),
            }
        }
    } else if webm.exists() && wav.exists() {
        println!("docs: no full ffmpeg found — narrated mux skipped (pip install imageio-ffmpeg)");
    }

    let _ = fs::remove_file(out.join(".sections.json"));
    let _ = fs::remove_dir_all(&tmp);

    // The man page is a projection of the same registry as usage().
    fs::write(out.join("brain.1"), crate::manual::man_page()).map_err(|e| e.to_string())?;

    // The artifacts become part of the twin under the full projection
    // contract: generated + expected_b3 + read-only bit, and screenshots
    // keep their provenance (which command produced them) in the graph
    // instead of a temp file that used to be deleted.
    twin::refresh(store, dir, prefix).map_err(|e| e.to_string())?;
    // Every output says which command produced it, not only the
    // screenshots: "where did this come from" is the first question a
    // person asks of a generated file.
    let mut provenance: Vec<(String, String)> = chapters
        .iter()
        .map(|c| (c.image.clone(), c.command()))
        .collect();
    let regenerate = format!("brain docs generate {} --prefix {prefix}", dir.display());
    for name in [
        "tour.md",
        "narration.txt",
        "tour.webm",
        "tour.wav",
        "tour-narrated.webm",
        "brain.1",
    ] {
        provenance.push((name.to_string(), regenerate.clone()));
    }
    record_projection(store, dir, out, prefix, &provenance).map_err(|e| e.to_string())?;
    println!(
        "docs regenerated under {} (read-only projection of {prefix}; edit the graph, not these files)",
        out.display()
    );
    Ok(())
}

/// Drop the read-only bit across a tree so regeneration can write.
fn set_tree_writable(out: &Path) {
    let mut stack = vec![out.to_path_buf()];
    while let Some(d) = stack.pop() {
        let Ok(entries) = fs::read_dir(&d) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
            } else if let Ok(meta) = fs::metadata(&path) {
                let mut perms = meta.permissions();
                if perms.readonly() {
                    perms.set_readonly(false);
                    let _ = fs::set_permissions(&path, perms);
                }
            }
        }
    }
}

/// The projection contract for every artifact under `out`: guarded
/// `generated=true` + `expected_b3` observations, the read-only bit, and
/// `rendered_from` provenance naming the command that produced each file.
///
/// Media outputs are additionally *declared as assets*, which is what
/// gives a screenshot a subtype, an owner and a place in `brain asset
/// list` instead of being an anonymous hashed file. They are deliberately
/// given no `depicts` targets: a tour screenshot summarises a whole query,
/// so listing the dozens of files behind it would mark it stale on every
/// unrelated edit. Its freshness comes from two exact signals instead —
/// `expected_b3` drift, and `tour::narration_drift`, which recomputes the
/// narration and names the sentence that stopped being true.
fn record_projection(
    store: &Store,
    dir: &Path,
    out: &Path,
    prefix: &str,
    provenance: &[(String, String)],
) -> Result<(), brain_store::StoreError> {
    use brain_index::{replay, Index as _, MemIndex};
    let mut index = MemIndex::new();
    replay(store, &mut index)?;
    let now = brain_store::now_ms();
    let owner = brain_core::ids::StableId::derive(&["repo", prefix]);
    let mut asset_edges = std::collections::BTreeSet::new();
    let mut stack = vec![out.to_path_buf()];
    while let Some(d) = stack.pop() {
        for entry in std::fs::read_dir(&d)? {
            let path = entry?.path();
            if path.is_dir() {
                stack.push(path);
                continue;
            }
            // dir is often "." and read_dir yields already-relative paths;
            // a failed strip means the path is already repo-relative.
            let rel = path.strip_prefix(dir).unwrap_or(&path);
            let rel = rel.to_string_lossy().replace('\\', "/");
            let sid = brain_core::ids::StableId::derive(&["file", &rel]);
            if index.entity_nodes(&sid).is_empty() {
                continue; // not a twinned extension; nothing to mark
            }
            let observe = |prop: &str, value: &str| -> Result<(), brain_store::StoreError> {
                store.put(&brain_core::object::Object::Observation {
                    subject: sid.clone(),
                    property: prop.to_string(),
                    value: value.to_string(),
                    source: "docsgen".to_string(),
                    observed_at_ms: now,
                })?;
                Ok(())
            };
            if twin::latest(&index, store, &sid, "generated")?.as_deref() != Some("true") {
                observe("generated", "true")?;
            }
            let hash = blake3::hash(&std::fs::read(&path)?).to_hex().to_string();
            if twin::latest(&index, store, &sid, "expected_b3")?.as_deref() != Some(hash.as_str()) {
                observe("expected_b3", &hash)?;
            }
            let out_rel = path
                .strip_prefix(out)
                .unwrap_or(&path)
                .to_string_lossy()
                .replace('\\', "/");
            if let Some((_, cmd)) = provenance.iter().find(|(p, _)| *p == out_rel) {
                if twin::latest(&index, store, &sid, "rendered_from")?.as_deref()
                    != Some(cmd.as_str())
                {
                    observe("rendered_from", cmd)?;
                }
            }
            // Pictures, screencasts and audio become typed assets; the
            // text projections already carry their own semantics.
            let subtype = assets::infer_subtype(&rel);
            if matches!(subtype, "image" | "screencast" | "audio") {
                assets::declare(
                    store,
                    &index,
                    &mut asset_edges,
                    prefix,
                    &rel,
                    &owner,
                    &[],
                    Some(subtype),
                    now,
                )?;
            }
            if let Ok(meta) = fs::metadata(&path) {
                let mut perms = meta.permissions();
                if !perms.readonly() {
                    perms.set_readonly(true);
                    let _ = fs::set_permissions(&path, perms);
                }
            }
        }
    }
    Ok(())
}

/// Run this same binary with args, capturing stdout.
fn self_out(args: &[&str]) -> Result<String, String> {
    let exe = std::env::current_exe().map_err(|e| e.to_string())?;
    let out = Command::new(exe)
        .args(args)
        .output()
        .map_err(|e| e.to_string())?;
    if !out.status.success() {
        return Err(format!(
            "brain {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&out.stderr)
        ));
    }
    Ok(String::from_utf8_lossy(&out.stdout).trim_end().to_string())
}

fn npm_global_root() -> Option<PathBuf> {
    let known = Path::new("/opt/node22/lib/node_modules");
    if known.join("playwright").exists() {
        return Some(known.to_path_buf());
    }
    let out = Command::new("npm").args(["root", "-g"]).output().ok()?;
    let root = PathBuf::from(String::from_utf8_lossy(&out.stdout).trim());
    root.join("playwright").exists().then_some(root)
}

fn find_ffmpeg() -> Option<String> {
    for cand in ["ffmpeg"] {
        if Command::new(cand)
            .arg("-version")
            .output()
            .is_ok_and(|o| o.status.success())
        {
            return Some(cand.to_string());
        }
    }
    let out = Command::new("python3")
        .args([
            "-c",
            "import imageio_ffmpeg; print(imageio_ffmpeg.get_ffmpeg_exe())",
        ])
        .output()
        .ok()?;
    if out.status.success() {
        let p = String::from_utf8_lossy(&out.stdout).trim().to_string();
        if !p.is_empty() {
            return Some(p);
        }
    }
    None
}

/// Probe a media file's duration in seconds via ffmpeg's -i banner.
fn duration_secs(ffmpeg: &str, file: &Path) -> Option<f64> {
    let out = Command::new(ffmpeg).arg("-i").arg(file).output().ok()?;
    let text = String::from_utf8_lossy(&out.stderr);
    let line = text.lines().find(|l| l.contains("Duration:"))?;
    let stamp = line.split("Duration:").nth(1)?.trim().split(',').next()?;
    let parts: Vec<&str> = stamp.split(':').collect();
    if parts.len() != 3 {
        return None;
    }
    let h: f64 = parts[0].parse().ok()?;
    let m: f64 = parts[1].parse().ok()?;
    let s: f64 = parts[2].parse().ok()?;
    Some(h * 3600.0 + m * 60.0 + s)
}

fn mux(ffmpeg: &str, webm: &Path, wav: &Path, out: &Path) -> Result<(), String> {
    let vdur = duration_secs(ffmpeg, webm).unwrap_or(0.0);
    let adur = duration_secs(ffmpeg, wav).unwrap_or(0.0);
    let pad = adur - vdur + 0.5;
    let status = if pad > 0.0 {
        // Narration outlasts the screencast: hold the last frame to its end.
        Command::new(ffmpeg)
            .args(["-y", "-loglevel", "error", "-i"])
            .arg(webm)
            .arg("-i")
            .arg(wav)
            .args([
                "-vf",
                &format!("tpad=stop_mode=clone:stop_duration={pad:.2}"),
            ])
            .args(["-c:v", "libvpx", "-b:v", "1M", "-c:a", "libopus"])
            .arg(out)
            .status()
    } else {
        Command::new(ffmpeg)
            .args(["-y", "-loglevel", "error", "-i"])
            .arg(webm)
            .arg("-i")
            .arg(wav)
            .args(["-c:v", "copy", "-c:a", "libopus", "-shortest"])
            .arg(out)
            .status()
    }
    .map_err(|e| e.to_string())?;
    if !status.success() {
        return Err("ffmpeg mux failed".to_string());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use brain_index::{replay, MemIndex};
    use brain_observe::twin::refresh;

    #[test]
    fn generated_media_is_marked_typed_and_traceable_to_its_command() {
        let root = tempfile::tempdir().unwrap();
        let out = root.path().join("docs/generated");
        std::fs::create_dir_all(out.join("img")).unwrap();
        std::fs::write(out.join("img/tests.png"), b"\x89PNG fake").unwrap();
        std::fs::write(out.join("tour.md"), "# Live tour\n").unwrap();

        let store = Store::open(&root.path().join(".brain")).unwrap();
        refresh(&store, root.path(), "twin/app").unwrap();

        let provenance = vec![
            (
                "img/tests.png".to_string(),
                "brain twin tests twin/app".to_string(),
            ),
            (
                "tour.md".to_string(),
                "brain docs generate . --prefix twin/app".to_string(),
            ),
        ];
        record_projection(&store, root.path(), &out, "twin/app", &provenance).unwrap();

        let mut index = MemIndex::new();
        replay(&store, &mut index).unwrap();
        let png = "docs/generated/img/tests.png";
        let sid = brain_core::ids::StableId::derive(&["file", png]);

        assert_eq!(
            twin::latest(&index, &store, &sid, "generated")
                .unwrap()
                .as_deref(),
            Some("true")
        );
        assert_eq!(
            twin::latest(&index, &store, &sid, "rendered_from")
                .unwrap()
                .as_deref(),
            Some("brain twin tests twin/app"),
            "a picture names the command that drew it"
        );
        assert!(twin::latest(&index, &store, &sid, "expected_b3")
            .unwrap()
            .is_some());
        assert!(
            std::fs::metadata(out.join("img/tests.png"))
                .unwrap()
                .permissions()
                .readonly(),
            "projections are armed read-only so drift is deliberate"
        );

        // The screenshot is a declared asset, not an anonymous hashed file.
        let rows = assets::list(&store, &index, "twin/app").unwrap();
        let shot = rows
            .iter()
            .find(|a| a.path == png)
            .expect("the screenshot is declared");
        assert_eq!(shot.subtype, "image");
        // Text projections carry their own semantics and are not assets.
        assert!(
            !rows.iter().any(|a| a.path.ends_with("tour.md")),
            "a markdown projection is not an asset"
        );

        // Re-recording an unchanged tree writes nothing.
        let before = store.count_objects().unwrap();
        record_projection(&store, root.path(), &out, "twin/app", &provenance).unwrap();
        assert_eq!(store.count_objects().unwrap(), before);
    }
}
