#!/usr/bin/env bash
# Always-up-to-date docs: every artifact in docs/generated/ is a projection
# of the live graph — regenerated wholesale, never edited by hand.
#
#   tour.md            the tour as markdown (query results, verbatim)
#   img/*.png          terminal screenshots (Playwright + bundled Chromium)
#   tour.webm          typed screencast of the same session
#   narration.txt      spoken script derived from graph state
#   tour-narrated.webm screencast + TTS narration track
#
# TTS backend: Qwen3-TTS-12Hz-0.6B-Base when its stack is installed (see
# scripts/docsgen/tts.py), espeak-ng otherwise.
#
# Usage: scripts/docsgen/generate.sh [dir] [prefix] [out-dir]
set -euo pipefail
DIR=${1:-.}
PREFIX=${2:-twin/self}
OUT=${3:-docs/generated}
BRAIN=${BRAIN_BIN:-target/debug/brain}
HERE=$(cd "$(dirname "$0")" && pwd)

"$BRAIN" twin refresh "$DIR" --prefix "$PREFIX" > /dev/null
mkdir -p "$OUT/img"

# ---- query the graph once; every artifact below projects these ----------
insights=$("$BRAIN" twin insights "$PREFIX")
matrix=$("$BRAIN" feature matrix "$PREFIX")
adrs=$("$BRAIN" adr list "$PREFIX")
tests=$("$BRAIN" twin tests "$PREFIX")
runs=$("$BRAIN" testrun list "$PREFIX")
stale=$("$BRAIN" twin stale "$PREFIX")

# ---- 1) tour.md ---------------------------------------------------------
{
  echo "# Live tour: \`$PREFIX\`"
  echo
  echo "> Generated by \`scripts/docsgen/generate.sh\` from the graph."
  echo "> Every section is a query result — regenerate, never edit."
  echo
  echo "## Insights (\`brain twin insights\`)"
  echo '```'; echo "$insights"; echo '```'
  echo
  echo "## Feature matrix — definition of done (\`brain feature matrix\`)"
  echo '```'; echo "$matrix"; echo '```'
  echo
  echo "## Decisions (\`brain adr list\`)"
  echo '```'; echo "$adrs"; echo '```'
  echo
  echo "## Tests (\`brain twin tests\`)"
  echo '```'; echo "$tests"; echo '```'
  echo
  echo "## Test protocols (\`brain testrun list\`)"
  echo '```'; echo "$runs"; echo '```'
  echo
  echo "## Doc staleness (\`brain twin stale\`)"
  echo '```'; echo "$stale"; echo '```'
  echo
  echo "![insights](img/insights.png)"
  echo
  echo "![feature matrix](img/matrix.png)"
  echo
  echo "Screencast: [tour.webm](tour.webm) — narrated: [tour-narrated.webm](tour-narrated.webm)"
} > "$OUT/tour.md"

# ---- 2) sections for capture + narration script -------------------------
python3 - "$OUT" <<'PY' \
  "brain twin insights::$insights" \
  "brain feature matrix::$matrix" \
  "brain adr list::$adrs" \
  "brain twin tests::$tests" \
  "brain testrun list::$runs"
import json, sys
out = sys.argv[1]
sections = []
ids = ["insights", "matrix", "decisions", "tests", "protocols"]
for i, arg in enumerate(sys.argv[2:]):
    cmd, text = arg.split("::", 1)
    sections.append({"id": ids[i], "cmd": cmd, "text": text})
with open(f"{out}/.sections.json", "w") as f:
    json.dump(sections, f)
PY

python3 "$HERE/narrate.py" "$PREFIX" "$OUT/.sections.json" > "$OUT/narration.txt"

# ---- 3) screenshots + screencast (Playwright, bundled Chromium) ---------
NODE_PATH=${NODE_PATH:-/opt/node22/lib/node_modules} \
  node "$HERE/capture.mjs" "$OUT" "$PREFIX"

# ---- 4) narration audio -------------------------------------------------
python3 "$HERE/tts.py" "$OUT/narration.txt" "$OUT/tour.wav" || {
  echo "tts: no backend available; narration.txt kept without audio"
}

# ---- 5) mux narration onto the screencast -------------------------------
# Needs a full ffmpeg (Playwright's bundled one is a video-only mux build):
# system ffmpeg, or `pip install imageio-ffmpeg` for a static binary.
FFMPEG=$(command -v ffmpeg \
  || python3 -c "import imageio_ffmpeg; print(imageio_ffmpeg.get_ffmpeg_exe())" 2>/dev/null \
  || true)
if [[ -n "$FFMPEG" && -f "$OUT/tour.webm" && -f "$OUT/tour.wav" ]]; then
  # ffmpeg -i (probe only) exits non-zero by design; don't let set -e trip.
  dur() { { "$FFMPEG" -i "$1" 2>&1 || true; } \
    | sed -n 's/.*Duration: \([0-9:.]*\),.*/\1/p' \
    | awk -F: '{ print ($1*3600)+($2*60)+$3 }'; }
  vdur=$(dur "$OUT/tour.webm"); adur=$(dur "$OUT/tour.wav")
  pad=$(awk -v a="$adur" -v v="$vdur" 'BEGIN { d = a - v + 0.5; print (d > 0 ? d : 0) }')
  if awk -v p="$pad" 'BEGIN { exit !(p > 0) }'; then
    # Narration outlasts the screencast: hold the last frame to its end.
    "$FFMPEG" -y -loglevel error -i "$OUT/tour.webm" -i "$OUT/tour.wav" \
      -vf "tpad=stop_mode=clone:stop_duration=$pad" \
      -c:v libvpx -b:v 1M -c:a libopus "$OUT/tour-narrated.webm"
  else
    "$FFMPEG" -y -loglevel error -i "$OUT/tour.webm" -i "$OUT/tour.wav" \
      -c:v copy -c:a libopus -shortest "$OUT/tour-narrated.webm"
  fi
  echo "narrated screencast: $OUT/tour-narrated.webm"
fi

rm -f "$OUT/.sections.json"
# ---- 6) the artifacts become part of the twin ---------------------------
"$BRAIN" twin refresh "$DIR" --prefix "$PREFIX" | tail -1
echo "docs regenerated under $OUT (projection of $PREFIX; do not edit)"
